/*
 * This Java source file was generated by the Gradle 'init' task.
 * 
 * Build: gradle build
 * Run: gradle run
 */
package list_ex;

import java.util.ArrayList;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public void compareListsWithUniqueElements() {
        List<String> l1 = new ArrayList<String>();
        l1.add("a");
        l1.add("b");
        l1.add("c");

        List<String> l2 = new ArrayList<String>();
        l2.add("b");
        l2.add("c");
        l2.add("d");

        List<String> l1c = new ArrayList<>(l1);
        List<String> l2c = new ArrayList<>(l2);

        l1c.removeAll(l2);
        l2c.removeAll(l1);

        System.out.println(l1c); // -> [a]
        System.out.println(l2c); // -> [d]
    }

    public void compareListsWithRepetingElements() {
        List<String> l1 = new ArrayList<String>();
        l1.add("a");
        l1.add("b");
        l1.add("b");
        l1.add("c");

        List<String> l2 = new ArrayList<String>();
        l2.add("b");
        l2.add("c");
        l2.add("c");
        l2.add("d");

        List<String> l1c = new ArrayList<String>(l1);
        List<String> l2c = new ArrayList<String>(l2);

        // removeAll removes all occurences of a string in a list
        // so although l2 contains one "b" it'll remove both "b" in l2
        l1c.removeAll(l2);
        l2c.removeAll(l1);

        System.out.println(l1);
        System.out.println(l2);
        System.out.println(l1c); // -> [a]
        System.out.println(l2c); // -> [d]

        l1c = new ArrayList<String>(l1);
        l2c = new ArrayList<String>(l2);
        
        for (String e: l2) {
            l1c.remove(e);
        }

        for (String e: l1) {
            l2c.remove(e);
        }

        System.out.println(l1c); // -> [a, b]
        System.out.println(l2c); // -> [c, d]
    }

    public static void main(String[] args) {
        App app = new App();
        app.compareListsWithUniqueElements();
        app.compareListsWithRepetingElements();
    }
}
