/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package false_sharing;

import org.testng.annotations.*;
import static org.testng.Assert.*;

public class FalseSharingTest {
    @Test public void appHasAGreeting() {
        FalseSharing classUnderTest = new FalseSharing();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
