/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gson.ex.gradle;

import java.util.List;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.Path;

public class GsonEx {

    public static void main(String... args) throws Exception {
        GsonEx gsonEx = new GsonEx();

        gsonEx.example1();
        gsonEx.example2();
    }

    public void example1() {
        String json = 
            "{"
                + "'title': 'Computing and Information systems',"
                + "'id' : 1,"
                + "'children' : 'true',"
                + "'groups' : [{"
                    + "'title' : 'Level one CIS',"
                    + "'id' : 2,"
                    + "'children' : 'true',"
                    + "'groups' : [{"
                        + "'title' : 'Intro To Computing and Internet',"
                        + "'id' : 3,"
                        + "'children': 'false',"
                        + "'groups':[]"
                    + "}]" 
                + "}]"
            + "}";

        // Now do the magic.
        Gson gson = new GsonBuilder().create();
        Data data = gson.fromJson(json, Data.class);

        // Show it.
        System.out.println(data);

    }

    public void example2() throws Exception {
        Path postsPath = Paths.get(".", "posts.json");

        byte[] postsBytes = Files.readAllBytes(postsPath);
        String json = new String(postsBytes, StandardCharsets.UTF_8);
        System.out.println("***** json *****");
        System.out.println(json);
        System.out.println("***** json e*****");

        // Now do the magic.
        Gson gson = new GsonBuilder().create();
        PostData posts = gson.fromJson(json, PostData.class);

        // Show it.
        System.out.println(posts);
    }

}

class Data {
    private String title;
    private Long id;
    private Boolean children;
    private List<Data> groups;

    public String getTitle() { return title; }
    public Long getId() { return id; }
    public Boolean getChildren() { return children; }
    public List<Data> getGroups() { return groups; }

    public void setTitle(String title) { this.title = title; }
    public void setId(Long id) { this.id = id; }
    public void setChildren(Boolean children) { this.children = children; }
    public void setGroups(List<Data> groups) { this.groups = groups; }

    public String toString() {
        return String.format("title:%s\nid:%d\nchildren:%s\ngroups:%s", title, id, children, groups);
    }
}

class PostData {
    public PageInfo pageInfo;
    public List<Post> posts;

    public String toString() {
        return String.format("pageInfo:%s\nlogo:%s", pageInfo.pageName, pageInfo.logo);
    }
}

class PageInfo {
    public String pageName;
    public String logo;
}

class Post {
    public String post_id;
    public String actor_id;
    public String author_name;
    public String post_title;
    public List<String> comments;
    public String time_of_post;
}
