/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package false_sharing;

public class FalseSharing {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new FalseSharing().getGreeting());
    }
}
